#!/bin/bash

#SBATCH -n 1
#SBATCH --time 15:00:00
#SBATCH --mem-per-cpu 100

#SBATCH -o scratch/ualaxr001/cosang_comp.log

#SBATCH -qos small
#SBATCH --mail-user=amrollins@crimson.ua.edu
#SBATCH --mail-type=ALL

module load mpich/3.4.1_slurm_intel18 gsl/2.5 hdf5/1.8.20

cd /home/ualaxr001/source_and_ic/cosang_code
make clean
make
